#Logging:
#  LogLevel:
#    Default: Information
#    Microsoft.AspNetCore: Warning

AllowedHosts: "*"

#Kestrel:
#  EndpointDefaults:
#    Protocols: Http2
    
Database:
  Host: localhost
  Port: 5432
  Database: outbox-db
  Username: postgres
  Password: postgres